runtime: python27
threadsafe: false
api_version: 1
handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|woff|woff2|ttf))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|woff|woff2|ttf))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
